#!/bin/bash
TESTS_FAILED=false
MAX_RETRIES=3
RETRY_DELAY=5

current_time=$(date +"%Y-%m-%d %H:%M:%S")
echo "Current Time: $current_time"

xvfb-run --server-args='-screen 0 1024x768x16 -ac' yarn run e2e

if [ $? -ne 0 ]; then
  echo "Cypress tests failed."
  TESTS_FAILED=true
fi

if [ -n "$REPORT_NAME" ]; then
  echo "Custom report name provided: $REPORT_NAME"
else
  timestamp=$(date +%Y%m%d-%H%M%S)
  REPORT_NAME="${timestamp}"
fi

report_dir="results/${REPORT_NAME}"

mkdir -p ${report_dir}

cp -rf results/mochawesome-report/assets/ ${report_dir}

./node_modules/.bin/mochawesome-merge 'results/*.json' > ${report_dir}/merge.json 
./node_modules/.bin/marge ${report_dir}/merge.json -o ${report_dir} -f index.html

